# Generated by Django 5.1.5 on 2025-01-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
