# Generated by Django 5.1.5 on 2025-03-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(),
        ),
    ]
